// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:87875c69-ba1e-4a9c-a7c9-be8c97ffaf24",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_0DP4185ny",
    "aws_user_pools_web_client_id": "4q7f95ijcvnh76qrp4m6adn6t9",
    "aws_cloud_logic_custom": [
        {
            "name": "api2068ffe3",
            "endpoint": "https://q8eylezaed.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        },
        {
            "name": "mbapi",
            "endpoint": "https://y7owxu0d7h.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "moviebuddy-20181222002356-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://moviebuddy-20181222002356-hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "postTable",
            "region": "us-east-1"
        },
        {
            "tableName": "replyTable",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
